version: '2'
services:
  mongo:
    image: mongo:4
#    ports:
#      - 27017:27017
    restart: always
    volumes:
      - ./mongo-data:/data/db

  massdb-import:
    build: ./node-massdb
    restart: always
    privileged: true
    environment:
      - DEBUG=*
    depends_on:
      - mongo
    volumes:
      - ./data:/data
    command: npm run cron

  massdb:
    build: ./node-massdb
    restart: always
#    volumes:
#      - ./node-massdb/src/src/server/staticPages:/node-massdb/src/server/staticPages
    environment:
      - DEBUG=*
    ports:
      - 12345:80
    depends_on:
      - mongo
