version: '2'
services:
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongo-data:/data/db

  node-massdb-import:
    build: ./node-massdb
    restart: always
    privileged: true
    depends_on:
      - mongo
    volumes:
      - ./data:/data
    command: npm run cron

  node-massdb:
    build: ./node-massdb
    restart: always
    ports:
      - 3001:80
    depends_on:
      - mongo
